### ISSUE TITLE
TOUCHR crack not working

### ISSUE THREAD

**Issue by gecko99** [W00dL3cs/PoGO-Tweak#1]
Hey man. So I downloaded your crack for the touchr app and it's not working on iOS 10, I went and purchased the developers license, but I can't find a way to get rid of the crack. Tried uninstalling and reinstalling multiple times, tried looking in the file system and cleaned with icleaner. Still says your name next to the license. If you could let me know how to delete it that'd be amazing. Here is my email marktrudeau1@gmail.com

**Comment by W00dL3cs** [comment]
Delete SuperDRM and you should be fine :)
