### ISSUE TITLE
[Help]. Can you tell me how to setup your project

### ISSUE THREAD

**Issue by ghost** [W00dL3cs/PoGO-Tweak#2]
I'm using xcode open your project and click run button then build failure.
Can you tell me step by step to setup your project?

here log: 
```
d: warning: directory not found for option '-L/Users/hoanghung/Library/Developer/Xcode/DerivedData/PoGO-Tweak-aikvinpurxkelfcpnlcgaeksulpm/Build/Products/Debug-iphoneos'
ld: warning: directory not found for option '-F/Users/hoanghung/Library/Developer/Xcode/DerivedData/PoGO-Tweak-aikvinpurxkelfcpnlcgaeksulpm/Build/Products/Debug-iphoneos'
ld: -ios_version_min argument is missing period as second character
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by W00dL3cs** [comment]
The project cannot be "run" from the Xcode environment directly: it has to be built, and then deployed to the device.
If you have iOSOpenDev installed, just change the device SSH details in the build settings, then choose "Generic iOS Device" as build target, and finally click Cmd+Shift+I to begin the install procedure.

**Comment by henrymark92** [comment]
Hi Alex.
I want learn how to build an ios tweak. Can you add my skype?
my skype: hunghoangthe92

**Comment by ghost** [comment]
Hi Alexandro.
I want learn to build a tweak ios. Can you share me any ebook or document?
Thanks

**Comment by W00dL3cs** [comment]
Of course!

You can find a lot of informations here (some stuff might be obsolete, tho): http://iphonedevwiki.net/index.php/Getting_Started

Or in case, you can try giving a look here: https://www.reddit.com/r/jailbreakdevelopers/

**Comment by henrymark92** [comment]
Hi Alexandro
I'm very glad know you. can you add my skype as contact.
my skype: hunghoangthe92

Thank so much
